services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./docker-config.yaml:/root/config.yaml
    ports:
      - "9999:9999"
    command: ./main
  migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile.migration
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pg-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pg-password}
      - POSTGRES_DB=${POSTGRES_DB:-tula-dev}
      - POSTGRES_HOST=${POSTGRES_HOST:-pg}
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: pgvector/pgvector:pg17
    container_name: pg
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pg-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pg-password}
      - POSTGRES_DB=${POSTGRES_DB:-tula-dev}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pg-user} -d ${POSTGRES_DB:-tula-dev}"]
      interval: 10s
      timeout: 5s
      retries: 5