volumes:
  pg_admin:

services:
  backend:
    image: ghcr.io/egortarasov/tuladays-2024/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./docker-config.yaml:/root/config.yaml
    ports:
      - "9999:9999"
    command: ./main
  migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile.migration
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pg-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pg-password}
      - POSTGRES_DB=${POSTGRES_DB:-tula-dev}
      - POSTGRES_HOST=${POSTGRES_HOST:-pg}
    depends_on:
      pg:
        condition: service_healthy
  telegram:
    image: ghcr.io/egortarasov/tuladays-2024/telegram:latest
    build:
      context: ./bot
      dockerfile: Dockerfile.telegram
    env_file:
      - .env
    depends_on:
      - pg
      - clickhouse
    ports:
      - "9900:8000"
  pg:
    image: pgvector/pgvector:pg17
    container_name: pg
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pg-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pg-password}
      - POSTGRES_DB=${POSTGRES_DB:-tula-dev}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pg-user} -d ${POSTGRES_DB:-tula-dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-tarasov.egor.yandex@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-cisco}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pg_admin:/var/lib/pgadmin
    ports:
      - "8888:80"
  clickhouse:
    image: clickhouse/clickhouse-server:23.3-alpine
    container_name: clickhouse
    hostname: clickhouse
    volumes:
    - ${PWD}/fs/volumes/clickhouse/users.d/users.xml:/etc/clickhouse-server/users.xml"
    ports:
    - "8123:8123"
    - "9990:9000"
    - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  grafana:
    build:
      context: ${PWD}/docker_files/
      dockerfile: grafana.Dockerfile
    container_name: tula-grafana
    hostname: grafana
    volumes:
      - ${PWD}/fs/volumes/grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse