# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'rag_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rag_service.proto\x12\x03rag\x1a\x1cgoogle/protobuf/struct.proto\"O\n\x13\x41\x64\x64\x44ocumentsRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12)\n\x08metadata\x18\x02 \x03(\x0b\x32\x17.google.protobuf.Struct\"&\n\x14\x41\x64\x64\x44ocumentsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"#\n\x12StreamQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"Q\n\x13StreamQueryResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12)\n\x08metadata\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct2\x95\x01\n\nRAGService\x12\x43\n\x0c\x41\x64\x64\x44ocuments\x12\x18.rag.AddDocumentsRequest\x1a\x19.rag.AddDocumentsResponse\x12\x42\n\x0bStreamQuery\x12\x17.rag.StreamQueryRequest\x1a\x18.rag.StreamQueryResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDDOCUMENTSREQUEST']._serialized_start=56
  _globals['_ADDDOCUMENTSREQUEST']._serialized_end=135
  _globals['_ADDDOCUMENTSRESPONSE']._serialized_start=137
  _globals['_ADDDOCUMENTSRESPONSE']._serialized_end=175
  _globals['_STREAMQUERYREQUEST']._serialized_start=177
  _globals['_STREAMQUERYREQUEST']._serialized_end=212
  _globals['_STREAMQUERYRESPONSE']._serialized_start=214
  _globals['_STREAMQUERYRESPONSE']._serialized_end=295
  _globals['_RAGSERVICE']._serialized_start=298
  _globals['_RAGSERVICE']._serialized_end=447
# @@protoc_insertion_point(module_scope)
