// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        int64
	Title     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Message struct {
	ID        int64
	ChatID    pgtype.Int8
	UserID    pgtype.Int8
	Text      string
	Metadata  []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type MessageStatus struct {
	MessageID int64
	UserID    int64
	Read      pgtype.Bool
	Notified  pgtype.Bool
}

type OauthProvider struct {
	ID   int32
	Name string
}

type OauthUser struct {
	ID             int32
	UserID         pgtype.Int4
	ProviderID     pgtype.Int4
	ProviderUserID string
}

type Role struct {
	ID   int32
	Name string
}

type Roster struct {
	ChatID int64
	UserID int64
}

type User struct {
	ID           int32
	Email        string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type UserRole struct {
	UserID int32
	RoleID int32
}
